/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GamePreview {
        /**
          * Background image URL. Falls back to theme-based image if not provided.
         */
        "backgroundimage": string;
        /**
          * Club Id (used for type 'swisshandball' only)
         */
        "club": string;
        /**
          * Game Id from my-club
         */
        "game": string;
        /**
          * Game Id from my-club for 2nd game
         */
        "game2": string;
        /**
          * Game Id from my-club for 3rd game
         */
        "game3": string;
        /**
          * Height of the preview
          * @default '1350'
         */
        "height": string;
        /**
          * Blur of the preview
          * @default ''
         */
        "imageblur": string;
        /**
          * Is this a home game?
          * @default false
         */
        "ishomegame": boolean;
        /**
          * Team Id (used for type 'swissvolley' and 'swisshandball' only)
         */
        "team": string;
        /**
          * Theme of the preview
          * @default 'myclub'
         */
        "theme": string;
        /**
          * CLub type
          * @default 'swissunihockey'
         */
        "type": string;
        /**
          * Width of the preview
          * @default '1080'
         */
        "width": string;
    }
    interface GameResult {
        /**
          * Background image URL. Falls back to theme-based image if not provided.
         */
        "backgroundimage": string;
        /**
          * Club Id (used for type 'swisshandball' only)
         */
        "club": string;
        /**
          * Game Id from my-club
         */
        "game": string;
        /**
          * Game Id from my-club for 2nd game
         */
        "game2": string;
        /**
          * Height of the preview
          * @default '1350'
         */
        "height": string;
        /**
          * Blur of the preview
          * @default ''
         */
        "imageblur": string;
        /**
          * Show result detail
          * @default false
         */
        "showresultdetail": boolean;
        /**
          * Team Id (used for type 'swissvolley' and 'swisshandball' only)
         */
        "team": string;
        /**
          * Theme of the preview
          * @default 'myclub'
         */
        "theme": string;
        /**
          * CLub type
          * @default 'swissunihockey'
         */
        "type": string;
        /**
          * Width of the preview
          * @default '1080'
         */
        "width": string;
    }
}
declare global {
    interface HTMLGamePreviewElement extends Components.GamePreview, HTMLStencilElement {
    }
    var HTMLGamePreviewElement: {
        prototype: HTMLGamePreviewElement;
        new (): HTMLGamePreviewElement;
    };
    interface HTMLGameResultElement extends Components.GameResult, HTMLStencilElement {
    }
    var HTMLGameResultElement: {
        prototype: HTMLGameResultElement;
        new (): HTMLGameResultElement;
    };
    interface HTMLElementTagNameMap {
        "game-preview": HTMLGamePreviewElement;
        "game-result": HTMLGameResultElement;
    }
}
declare namespace LocalJSX {
    interface GamePreview {
        /**
          * Background image URL. Falls back to theme-based image if not provided.
         */
        "backgroundimage"?: string;
        /**
          * Club Id (used for type 'swisshandball' only)
         */
        "club"?: string;
        /**
          * Game Id from my-club
         */
        "game"?: string;
        /**
          * Game Id from my-club for 2nd game
         */
        "game2"?: string;
        /**
          * Game Id from my-club for 3rd game
         */
        "game3"?: string;
        /**
          * Height of the preview
          * @default '1350'
         */
        "height"?: string;
        /**
          * Blur of the preview
          * @default ''
         */
        "imageblur"?: string;
        /**
          * Is this a home game?
          * @default false
         */
        "ishomegame"?: boolean;
        /**
          * Team Id (used for type 'swissvolley' and 'swisshandball' only)
         */
        "team"?: string;
        /**
          * Theme of the preview
          * @default 'myclub'
         */
        "theme"?: string;
        /**
          * CLub type
          * @default 'swissunihockey'
         */
        "type"?: string;
        /**
          * Width of the preview
          * @default '1080'
         */
        "width"?: string;
    }
    interface GameResult {
        /**
          * Background image URL. Falls back to theme-based image if not provided.
         */
        "backgroundimage"?: string;
        /**
          * Club Id (used for type 'swisshandball' only)
         */
        "club"?: string;
        /**
          * Game Id from my-club
         */
        "game"?: string;
        /**
          * Game Id from my-club for 2nd game
         */
        "game2"?: string;
        /**
          * Height of the preview
          * @default '1350'
         */
        "height"?: string;
        /**
          * Blur of the preview
          * @default ''
         */
        "imageblur"?: string;
        /**
          * Show result detail
          * @default false
         */
        "showresultdetail"?: boolean;
        /**
          * Team Id (used for type 'swissvolley' and 'swisshandball' only)
         */
        "team"?: string;
        /**
          * Theme of the preview
          * @default 'myclub'
         */
        "theme"?: string;
        /**
          * CLub type
          * @default 'swissunihockey'
         */
        "type"?: string;
        /**
          * Width of the preview
          * @default '1080'
         */
        "width"?: string;
    }
    interface IntrinsicElements {
        "game-preview": GamePreview;
        "game-result": GameResult;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "game-preview": LocalJSX.GamePreview & JSXBase.HTMLAttributes<HTMLGamePreviewElement>;
            "game-result": LocalJSX.GameResult & JSXBase.HTMLAttributes<HTMLGameResultElement>;
        }
    }
}
