/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GamePreviewWebComponent {
        "game": string;
        /**
          * Game Id from my-club
         */
        "gameId": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLGamePreviewWebComponentElement extends Components.GamePreviewWebComponent, HTMLStencilElement {
    }
    var HTMLGamePreviewWebComponentElement: {
        prototype: HTMLGamePreviewWebComponentElement;
        new (): HTMLGamePreviewWebComponentElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "game-preview-web-component": HTMLGamePreviewWebComponentElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface GamePreviewWebComponent {
        "game"?: string;
        /**
          * Game Id from my-club
         */
        "gameId"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "game-preview-web-component": GamePreviewWebComponent;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "game-preview-web-component": LocalJSX.GamePreviewWebComponent & JSXBase.HTMLAttributes<HTMLGamePreviewWebComponentElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
