/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GamePreview {
        /**
          * Club Id from my-club
         */
        "club": string;
        /**
          * Game Id from my-club
         */
        "game": string;
        /**
          * Height of the preview
          * @default '400'
         */
        "height": string;
        /**
          * Theme of the preview
          * @default 'myclub'
         */
        "theme": string;
        /**
          * Width of the preview
          * @default '400'
         */
        "width": string;
    }
}
declare global {
    interface HTMLGamePreviewElement extends Components.GamePreview, HTMLStencilElement {
    }
    var HTMLGamePreviewElement: {
        prototype: HTMLGamePreviewElement;
        new (): HTMLGamePreviewElement;
    };
    interface HTMLElementTagNameMap {
        "game-preview": HTMLGamePreviewElement;
    }
}
declare namespace LocalJSX {
    interface GamePreview {
        /**
          * Club Id from my-club
         */
        "club"?: string;
        /**
          * Game Id from my-club
         */
        "game"?: string;
        /**
          * Height of the preview
          * @default '400'
         */
        "height"?: string;
        /**
          * Theme of the preview
          * @default 'myclub'
         */
        "theme"?: string;
        /**
          * Width of the preview
          * @default '400'
         */
        "width"?: string;
    }
    interface IntrinsicElements {
        "game-preview": GamePreview;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "game-preview": LocalJSX.GamePreview & JSXBase.HTMLAttributes<HTMLGamePreviewElement>;
        }
    }
}
